### ISSUE TITLE
Community on Discord or Slack 

### ISSUE THREAD

**Issue by Angelk90** [mrousavy/react-native-vision-camera#1747]
### Question

Hi @mrousavy, as previously mentioned it would be useful to have a Community on Discord or Slack.

P.S.

When I clone the project it takes a long time, the problem is not with the connection, but there are about 85 branches.

Many of which are `dependabot` or old branches already committed and never deleted.

**Comment by mrousavy** [comment]
Hey - just created a discord: https://discord.gg/6CSHz2qAvA
