### ISSUE TITLE
🐛 IOS17.0.3, iPhone14 Pro takePhoto method bug 

### ISSUE THREAD

**Issue by LESANF** [mrousavy/react-native-vision-camera#1961]
### What's happening?

It's an app on sale now and I'm taking pictures using vision-camera.

Since the recent ios17 update came out, the takephoto function has conditionally failed to work well.

The current models are available for all iPhones with less than 17 versions.

The model that found the bug was when the iPhone 14 Pro was 17.0.2 and 17.0.3.

iPhone 14 Pro worked well when it was IOS 16 version.

One thing I wonder is that it works well on the iPhone 12 IOS 17.

Below is the operating image of my app.

https://github.com/mrousavy/react-native-vision-camera/assets/54767632/69bd609b-89fd-4f8b-a37f-a29b536166fa

https://github.com/mrousavy/react-native-vision-camera/assets/54767632/fdac5101-b233-404a-a4c9-3859aa842178

In case of failure, the path of the photo was not received.

Currently, I can't test because IOS 17.0.3's practical machine connection is not supported on xcode 15, so I distribute the app through firebase and debug it. (Please point out if I'm mistaken. connection to the practical machine for 17.0.3)

Tell me if the problem is vision-camera or something else. I need a lot of help

### Reproduceable Code

```tsx
const photo = 
    Platform.OS === 'ios'
        ? await cameraRef.current.takePhoto({
            flash: 'off',
          })
        : await cameraRef.current.takeSnapshot({
            quality: 80,
            flash: 'off',
          });

let rotatedUri = photo.path;
```

### Relevant log output

```shell
This is the case where you cannot take a log in a test environment.

I distributed the app on firebase and checked it by putting the photo.path value in alert,

and if it failed, nothing appeared, and if it was successful, 

the path printed it normally.
In the video above, nothing came up when it was failed.
```

### Camera Device

```json
-
```

### Device

iPhone 14 Pro(IOS 17.0.2, 17.0.3)

### VisionCamera Version

2.15.4, 2.16.2

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey, glad to hear you're using VisionCamera in production and everything worked fine so far.

I don't offer any free support for bug-hunting for V2 anymore, so either upgrade to V3 or reach out to me through my consultancy agency so we can take a look at this for an hourly rate.

**Comment by mrousavy** [comment]
And even if, I would need the logs. Maybe you can get those somehow with `Console.app`
